# Single-leg reorganization setup
# Run from examples/reorg_md
ligand_base: ./ligands
ligand_batch:
  - LIG

# Produced by prepare_inputs.py
protein: ./pdbs/3pzw_sub_full_no_lig.pdb

output_base: ./reorg_runs

# Disable Boresch for reorg-style single-leg decoupling
boresch: null

complex:
  num_procs: -1
  box_shape: dodecahedron
  buffer: 15.0
  neutralize: true
  ionic_strength: 0.15
  do_hmr: true
  hydrogen_mass: 3.024
  water_model: tip3p
  protein_ff:
    - amber14-all.xml
  water_ff:
    - amber14/tip3p.xml
  extra_ff:
    - ./ffxml/AN1.xml
    - ./ffxml/FE1.xml
    - ./ffxml/HD1.xml
    - ./ffxml/HD2.xml
    - ./ffxml/HD3.xml
    - ./ffxml/IE1.xml
    - ./ffxml/O11.xml
    - ./ffxml/mcpb_metal_params.xml

  workflow:
    - type: em
      name: 01.em
      exec: pmemd.cuda
      use_remd: false
      use_mpi: false
      cntrl:
        maxcyc: 2000
        ofreq: 100
        ntr: 1
        restraint_wt: 10.0
        restraintmask: ':LIG & !@H='

    - type: heat
      name: 02.heat
      exec: pmemd.cuda
      use_remd: false
      use_mpi: true
      cntrl:
        nstlim: 12500
        dt: 0.002
        ofreq: 1250
        ntr: 1
        restraint_wt: 10.0
        restraintmask: ':LIG & !@H='

    - type: pres
      name: 03.pres
      exec: pmemd.cuda
      use_remd: false
      use_mpi: true
      cntrl:
        nstlim: 12500
        dt: 0.002
        ofreq: 1250
        ntr: 1
        restraint_wt: 10.0
        restraintmask: ':LIG & !@H='

    - type: prod
      name: 04.pre_prod
      exec: pmemd.cuda
      use_remd: false
      use_mpi: true
      cntrl:
        nstlim: 125000
        dt: 0.004
        ofreq: 12500
        ntr: 1
        restraint_wt: 5.0
        restraintmask: ':LIG & !@H='

    - type: prod
      name: 05.prod
      exec: pmemd.cuda
      use_remd: true
      use_mpi: true
      cntrl:
        nstlim: 125
        dt: 0.004
        ofreq: 12500
        numexchg: 10000
        ntr: 1
        restraint_wt: 5.0
        restraintmask: ':LIG & !@H='

  use_charge_change: false
  use_settle_for_alchemical_water: true
  lambdas:
    - 0.0
    - 0.06666666666666667
    - 0.13333333333333333
    - 0.2
    - 0.26666666666666666
    - 0.3333333333333333
    - 0.4
    - 0.4666666666666667
    - 0.5333333333333333
    - 0.6
    - 0.6666666666666666
    - 0.7333333333333333
    - 0.8
    - 0.8666666666666667
    - 0.9333333333333333
    - 1.0
  num_lambdas: 16
